#!/usr/bin/env ruby
# frozen_string_literal: true

# macOS用インストーラーのテンプレート
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'tty'
end

require 'tty-command'
require 'tty-spinner'
require 'tty-prompt'
require 'tty-box'
require 'pastel'
require "fileutils"

box = TTY::Box.frame(
  width: 50,
  height: 5,
  padding: 1,
  align: :center,
  title: { top_left: ' SUPPLEMENT ' },
  border: :thick,
  style: {
    fg: :cyan, # 枠線の色
    border: { fg: :cyan }
  }
) do
  'Install supplements for macOS.'
end
print box

HOME_ROOT = File.expand_path("~")

FileUtils.chdir HOME_ROOT do
  puts "Start install supplements for macOS."
  puts "pwd: #{Dir.pwd}"
  puts "Finished install supplements for macOS."
end
