#!/usr/bin/env ruby
# frozen_string_literal: true

# macOS用インストーラーのテンプレート
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'tty' # これ1つで全部入り！
end

require 'tty-command'
require 'tty-spinner'
require 'tty-prompt'
require 'tty-box'
require 'pastel'
require "fileutils"

box = TTY::Box.frame(
  width: 50,
  height: 5,
  padding: 1,
  align: :center,
  title: { top_left: ' SUPPLEMENT ' },
  border: :thick,
  style: {
    fg: :cyan, # 枠線の色
    border: { fg: :cyan }
  }
) do
  'Install supplements for Omarchy.'
end
print box

def system!(*)
  system(*, exception: true)
end

HOME_ROOT = File.expand_path("~")

FileUtils.chdir HOME_ROOT do
  puts "Start install supplements for Omarchy."
  puts "pwd: #{Dir.pwd}"

  system! "install-packages"
  system! "install-middleware"
  system! "install-dotfiles"
  system! "install-hyprland-overrides"
  system! "setup-packages"

  puts "Finished install supplements for Omarchy."
end
